-- TAD seed: 145 records
INSERT OR IGNORE INTO tad (nama, jabatan, penempatan) VALUES
  ('Eko Setiawan', 'Operator', 'ULD BABAI'),
  ('Syamsuri', 'Operator', 'ULD BABAI'),
  ('Dolarman', 'Operator', 'ULD BABAI'),
  ('Hasim', 'Operator', 'ULD BABAI'),
  ('Fahrija Rahman', 'Operator', 'ULD BABAI'),
  ('Ramadhani', 'Operator', 'ULD BABAI'),
  ('Randa Yudistira', 'Operator', 'ULD BABAI'),
  ('Muhammad Kelvin', 'Operator', 'ULD BABAI'),
  ('Alfianor', 'Operator', 'ULD BABAI'),
  ('Ahmat Rida', 'Operator', 'ULD GUNUNG PUREI'),
  ('Supiansyah', 'Operator', 'ULD GUNUNG PUREI'),
  ('Fahmi', 'Operator', 'ULD GUNUNG PUREI'),
  ('Minghuandy', 'Operator', 'ULD GUNUNG PUREI'),
  ('Nurahman', 'Operator', 'ULD GUNUNG PUREI'),
  ('Eko Setiawan', 'Operator', 'ULD GUNUNG PUREI'),
  ('Husliansyah', 'Operator', 'ULD GUNUNG PUREI'),
  ('Aryuni', 'Operator', 'ULD KENAMBUI'),
  ('Muliyarta', 'Operator', 'ULD KENAMBUI'),
  ('Erwansyah', 'Operator', 'ULD KENAMBUI'),
  ('Gusti Gustira', 'Operator', 'ULD KENAMBUI'),
  ('M Arbani', 'Operator', 'ULD KENAMBUI'),
  ('Sandi', 'Operator', 'ULD KENAMBUI'),
  ('Suhaimi', 'Operator', 'ULD KENAMBUI'),
  ('Amriansyah', 'Operator', 'ULD KENAMBUI'),
  ('Rusdiansyah', 'Operator', 'ULD KENAMBUI'),
  ('Junika Cucu Andika', 'Operator', 'ULD KENAMBUI'),
  ('Alex Sanderia', 'Operator', 'ULD KUDANGAN'),
  ('Timbun Radiyanto', 'Operator', 'ULD KUDANGAN'),
  ('Hery Optianus', 'Operator', 'ULD KUDANGAN'),
  ('Sabriansyah', 'Operator', 'ULD KUDANGAN'),
  ('Donny Prayogo', 'Operator', 'ULD KUDANGAN'),
  ('Yosuarius YB', 'Operator', 'ULD KUDANGAN'),
  ('Anto', 'Operator', 'ULD KUDANGAN'),
  ('Basilius Yoga', 'Operator', 'ULD KUDANGAN'),
  ('Aripin', 'Operator', 'ULD MENDAWAI'),
  ('Tomi Kuswoyo', 'Operator', 'ULD MENDAWAI'),
  ('Mujianor', 'Operator', 'ULD MENDAWAI'),
  ('Didin Wahono', 'Operator', 'ULD MENDAWAI'),
  ('Zulkifli', 'Operator', 'ULD MENDAWAI'),
  ('Hendri Purwanto', 'Operator', 'ULD MENDAWAI'),
  ('Moh Taufiq', 'Operator', 'ULD MENDAWAI'),
  ('M Ardianor', 'Operator', 'ULD MENDAWAI'),
  ('Yoga Syahbandi', 'Operator', 'ULD MENDAWAI'),
  ('Azkia El Murthada', 'Operator', 'ULD MENDAWAI'),
  ('Rafdianor', 'Operator', 'ULD MENDAWAI'),
  ('Hidayat Saputra', 'Operator', 'ULD PAGATAN'),
  ('Abdul Haris', 'Operator', 'ULD PAGATAN'),
  ('Muhammad Pauzan', 'Operator', 'ULD PAGATAN'),
  ('Tedy Heriady', 'Operator', 'ULD PAGATAN'),
  ('Murdiansyah', 'Operator', 'ULD PAGATAN'),
  ('Ridy', 'Operator', 'ULD PAGATAN'),
  ('Megi', 'Operator', 'ULD PAGATAN'),
  ('Muhammad Hidayat', 'Operator', 'ULD PAGATAN'),
  ('Muhammad Ikhsan', 'Operator', 'ULD PAGATAN'),
  ('Muhammad Abidin', 'Operator', 'ULD RANGGA ILUNG'),
  ('Hendra Prianto', 'Operator', 'ULD RANGGA ILUNG'),
  ('M Ilham', 'Operator', 'ULD RANGGA ILUNG'),
  ('Hendri Irawan', 'Operator', 'ULD RANGGA ILUNG'),
  ('Ahmad Jainudin', 'Operator', 'ULD RANGGA ILUNG'),
  ('Muhammad Ari Sutarinda', 'Operator', 'ULD RANGGA ILUNG'),
  ('Alvyus Advent Bagaskara', 'Operator', 'ULD RANGGA ILUNG'),
  ('Murjoko', 'Operator', 'ULD TELAGA'),
  ('Adi Rahmad', 'Operator', 'ULD TELAGA'),
  ('Irawan', 'Operator', 'ULD TELAGA'),
  ('Eko Prasetyo', 'Operator', 'ULD TELAGA PULANG'),
  ('Mulyadi', 'Operator', 'ULD TELAGA PULANG'),
  ('Tri Wahyono', 'Operator', 'ULD TELAGA PULANG'),
  ('Adi Susanto', 'Operator', 'ULD TELAGA PULANG'),
  ('Karnadie', 'Operator', 'ULD TELAGA PULANG'),
  ('Didie', 'Operator', 'ULD TELAGA PULANG'),
  ('Yesto', 'Operator', 'ULD TELAGA PULANG'),
  ('Ahmad Boby Erlangga', 'Operator', 'ULD TELAGA PULANG'),
  ('Effendi', 'Operator', 'ULD TUMBANG MANJUL'),
  ('A Rafiq', 'Operator', 'ULD TUMBANG MANJUL'),
  ('Mulyadi', 'Operator', 'ULD TUMBANG MANJUL'),
  ('Supian', 'Operator', 'ULD TUMBANG MANJUL'),
  ('Alpian', 'Operator', 'ULD TUMBANG MANJUL'),
  ('Gusna Nubin', 'Operator', 'ULD TUMBANG MANJUL'),
  ('M Ipan Ali', 'Operator', 'ULD TUMBANG MANJUL'),
  ('Wardani', 'Operator', 'ULD TUMBANG MANJUL'),
  ('Alpianor', 'Operator', 'ULD TUMBANG MANJUL'),
  ('Juljalali Wal Ikram', 'Operator', 'ULD TUMBANG MANJUL'),
  ('Naneng Ermadi', 'Operator', 'ULD TUMBANG SENAMANG'),
  ('Ahmad Budi Santoso', 'Operator', 'ULD TUMBANG SENAMANG'),
  ('Yudi Setiono', 'Operator', 'ULD TUMBANG SENAMANG'),
  ('Burhan', 'Operator', 'ULD TUMBANG SENAMANG'),
  ('Sutrisman', 'Operator', 'ULD TUMBANG SENAMANG'),
  ('Purwanto', 'Operator', 'ULD TUMBANG SENAMANG'),
  ('Muhammad Nudie', 'Operator', 'ULD TUMBANG SENAMANG'),
  ('Benny Rahmadani', 'Operator', 'ULD TUMBANG SENAMANG'),
  ('Dodi Kurniawan', 'Operator', 'ULD TUMBANG SENAMANG'),
  ('Deniasyah', 'Operator', 'ULD MANGKATIP'),
  ('Sukardiono', 'Operator', 'ULD MANGKATIP'),
  ('Tajudin', 'Operator', 'ULD MANGKATIP'),
  ('Alvyus Advent Bagaskara', 'Operator', 'ULD MANGKATIP'),
  ('M Ilman', 'Operator', 'ULD MANGKATIP'),
  ('Hendri Aprius', 'Operator', 'ULD TELUK BETUNG'),
  ('Kanserto', 'Operator', 'ULD TELUK BETUNG'),
  ('Gupinda Ramadan', 'Operator', 'ULD TELUK BETUNG'),
  ('M Indra Saputra', 'Operator', 'ULD TELUK BETUNG'),
  ('Achrian Noor', 'Operator', 'ULD TELUK BETUNG'),
  ('Rizki Permana', 'Operator', 'ULD TELUK BETUNG'),
  ('Jihad', 'Operator', 'ULD TELUK BETUNG'),
  ('Herianor', 'Operator', 'ULD TUMPUNG LAUNG'),
  ('Yatno Eka Nugraha', 'Operator', 'ULD TUMPUNG LAUNG'),
  ('Murjani', 'Operator', 'ULD TUMPUNG LAUNG'),
  ('Masrawan', 'Operator', 'ULD TUMPUNG LAUNG'),
  ('Yuspida', 'Operator', 'ULD TUMPUNG LAUNG'),
  ('Agus Salim', 'Operator', 'ULD TUMPUNG LAUNG'),
  ('Lambri', 'Operator', 'ULD TUMPUNG LAUNG'),
  ('Budi Hermonika Sosilo', 'Operator', 'ULD TUMPUNG LAUNG'),
  ('N Hirliyadi', 'Operator', 'ULD SUNGAI BALI'),
  ('Husni Mubarak', 'Operator', 'ULD SUNGAI BALI'),
  ('Bahrianor', 'Operator', 'ULD SUNGAI BALI'),
  ('Muhammad Randi', 'Operator', 'ULD SUNGAI BALI'),
  ('Gilang Ramadhan', 'Operator', 'ULD SUNGAI BALI'),
  ('Muhammad Noviar Rahman', 'Operator', 'ULD SUNGAI BALI'),
  ('Muhammad Riansyah', 'Operator', 'ULD SUNGAI BALI'),
  ('Masriansyah', 'Operator', 'ULD SUNGAI BALI'),
  ('Arwin', 'Operator', 'ULD KERASIAN'),
  ('Darmawi', 'Operator', 'ULD KERASIAN'),
  ('Indrayadi', 'Operator', 'ULD KERASIAN'),
  ('Padli', 'Operator', 'ULD KERASIAN'),
  ('Suaib', 'Operator', 'ULD KERASIAN'),
  ('Suhardi', 'Operator', 'ULD KERASIAN'),
  ('Agus', 'Operator', 'ULD KERAYAAN'),
  ('Alwir', 'Operator', 'ULD KERAYAAN'),
  ('Khabir', 'Operator', 'ULD KERAYAAN'),
  ('M Said', 'Operator', 'ULD KERAYAAN'),
  ('Masjoni', 'Operator', 'ULD KERAYAAN'),
  ('Muhammad Noor', 'Operator', 'ULD KERAYAAN'),
  ('Roni Marten', 'Operator', 'ULD KERAYAAN'),
  ('Abd Sapma', 'Operator', 'ULD KERUMPUTAN'),
  ('Fahrudin', 'Operator', 'ULD KERUMPUTAN'),
  ('Hidayatullah', 'Operator', 'ULD KERUMPUTAN'),
  ('Paesal', 'Operator', 'ULD KERUMPUTAN'),
  ('Rasdi', 'Operator', 'ULD KERUMPUTAN'),
  ('Safriansyah', 'Operator', 'ULD KERUMPUTAN'),
  ('Dedi Yusuf', 'Operator', 'ULD MARABATUAN'),
  ('Febrianto', 'Operator', 'ULD MARABATUAN'),
  ('Hamsyah', 'Operator', 'ULD MARABATUAN'),
  ('Hasdiansyah', 'Operator', 'ULD MARABATUAN'),
  ('Pardiansyah', 'Operator', 'ULD MARABATUAN'),
  ('Sri Ekonanto', 'Operator', 'ULD MARABATUAN'),
  ('Wahyudin', 'Operator', 'ULD MARABATUAN');
